'use client'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import {
  QueryClient,
  QueryClientProvider,
} from 'react-query'
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'User posts',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const queryclient = new QueryClient();
  return (
    <html lang="en">
      <head>
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css"
          />
      </head>
      <body className={`relative ${inter.className}`}>
        <div className='w-full flex flex-col bg-slate-100/50 min-h-screen pt-14 px-12'>
        <QueryClientProvider client={queryclient}>
          <Header />
          {children}
          <Footer />
        </QueryClientProvider>
        </div>
      </body>
    </html>
  )
}
